# Generated by Django 4.1.6 on 2023-09-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_order_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
